# Generated by Django 4.1.4 on 2025-02-11 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={},
        ),
    ]
