# Generated by Django 4.1.4 on 2025-02-12 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CatDatabase', '0002_alter_cat_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('TreatmentID', models.AutoField(primary_key=True, serialize=False)),
                ('TreatmentName', models.CharField(max_length=200)),
                ('StartDate', models.DateField(blank=True)),
                ('EndDate', models.DateField(blank=True)),
                ('Description', models.CharField(max_length=1000)),
                ('CatID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CatDatabase.cat')),
            ],
        ),
    ]
