# Generated by Django 4.1.4 on 2025-02-12 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CatDatabase', '0003_treatment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('ReportID', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField(blank=True)),
                ('Details', models.CharField(max_length=1000)),
                ('ReportType', models.CharField(max_length=100)),
                ('CatID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CatDatabase.cat')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('MedicationID', models.AutoField(primary_key=True, serialize=False)),
                ('MedicationName', models.CharField(max_length=200)),
                ('Dosage', models.IntegerField()),
                ('Frequency', models.IntegerField()),
                ('Description', models.CharField(max_length=1000)),
                ('TreatmentID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CatDatabase.treatment')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('AppointmentID', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField(blank=True)),
                ('Time', models.TimeField(blank=True)),
                ('Reason', models.CharField(max_length=500)),
                ('CatID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CatDatabase.cat')),
                ('UserID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
